### ISSUE TITLE
Update configure.py 

### ISSUE THREAD

**Issue by ssiekmann** [PortlandAssembly/The-project#13]
user.py prompts
number formatting
something better than readline

**Comment by blujan** [comment]
This managed to get the more interactive input working on my dev setup. Let me know if this looks good on your end.

**Comment by goldenapples** [comment]
Aside from the one bug I noted with the phone number regex, it all works for me, and is a lot easier to use than the original prompts I had there.

A few thoughts that might make it even better:
- we could probably validate the length of the SID and token to give users a warning, in case they missed a character while copying it.
- we could trim surrounding whitespace from all the inputs before validating or saving them. I know trying to copy the ngrok url I keep accidentally copying a tab or space character after it, and that messes up the endpoint to /api/message that the script tries to build.

**Comment by blujan** [comment]
I as debating doing the SID, but might as well go all out and completely agree on the whitespace removal.

**Comment by goldenapples** [comment]
I think this process is much improved. OK to close this issue?

**Comment by blujan** [comment]
Good with me. I just left it open for someone to double check.
