### ISSUE TITLE
Brainstorm for names

### ISSUE THREAD

**Issue by goldenapples** [PortlandAssembly/The-project#14]
Just an open thread for asynchronous brainstorming of names, etc. for the project.

**Comment by goldenapples** [comment]
I had the idea for "ALERTA", except that there's apparently already a monitoring tool with that name. :disappointed:

**Comment by blujan** [comment]
Along that line, the root verb is "alertar" with "alertan" being the present "they" form or "alertamos" being the "we" form.

**Comment by goldenapples** [comment]
Could work. I think the imperative tense works better, but maybe a different conjugation would help to make the name unique.

We could also add something to it to distinguish it. Like "net alerta", since that's what you're doing, putting your network on alert. Or, since network in Spanish is "red", we could go for the full bilingual pun at "red alerta".

**Comment by blujan** [comment]
Heh. I like the pun idea, but it seems that there's already some software out there with that name: https://redalerta.ec/nuevo/. It looks like a home security system/app. Though, it might be localized to Ecuador. So, might be ok?

Also this reminds me of something for v2 that I'm not sure got on the list: multilingual support.

**Comment by goldenapples** [comment]
"heyer" is also potentially a good name.

**Comment by blujan** [comment]
I was actually thinking the last name might be a better choice. It's almost close to "hey" as a means to get someone's attention. If we want to go full web2.0 we could make it "Heyr" lol.

**Comment by blujan** [comment]
Thoughts on combining the two ideas? Heyer Alerta?

**Comment by goldenapples** [comment]
I like it! Pronounced like "higher alert"?

**Comment by blujan** [comment]
I didn't even make that connection but yea!

**Comment by goldenapples** [comment]
Also, I was thinking with regard to getting permission for the name - I'm not sure that's necessary now. It'd be nice to have the blessing of Heather's comrades or family, but I wouldn't want to hassle them too much about it. Her name is already symbolic of a lot of things in the general culture (see [Heather Heyer Brigade](https://www.pri.org/stories/2017-09-06/antifa-has-rapid-response-team-targets-alt-right-organizers), [Heather Heyer Park](http://www.nydailynews.com/new-york/queens-pol-rename-trump-state-park-heather-heyer-article-1.3474860), etc.) As long as we're in the same tradition, I think it would be perfectly valid to use the name.

"Alerta" I'm not concerned at all about. That's been an anti-fascist slogan for 80 years or more; if anything the tech companies using it should have to feel bad about co-opting it.

**Comment by blujan** [comment]
Yea, I've seen Heyer show up on posters in Greece even. So, I'm not too worried about using it at this point either.

**Comment by ssiekmann** [comment]
I LOVE Heyer Alert(a). I think this is a very good name. 

+1
