### ISSUE TITLE
Adopt code of conduct, documentation for contributors, etc.

### ISSUE THREAD

**Issue by goldenapples** [PortlandAssembly/The-project#2]
Geek Feminism has a [list of existing CoC policies](http://geekfeminism.wikia.com/wiki/Code_of_conduct_evaluations) that we can look over and borrow/steal from.

We could make sure to include the points from [PA's principles](https://portlandassembly.com/about/principles-and-vision/), to the degree that they help articulate a viewpoint.

Finally, we just need to agree on a decision-making process. Do all members need to sign off on a PR before merging, or is a majority vote good enough? Can feature or bugfix PRs be merged with a single review or does everything need a full discussion? etc.

**Comment by blujan** [comment]
I rather like [Geek Feminism's CoC](https://geekfeminism.org/about/code-of-conduct/) itself, and they make it easy to adopt. The only thing we'll have to decide upon is the process for how we handle harassment/abuse reports.

As for the other issue, I'm ok with just a single review for the time being unless it's for a major feature. In which case, it would need to be reviewed by everyone. Of course, have a loose definition of what constitutes a "major feature" might be useful, but for the most part, I think leaving that to be subjective will be fine.

**Comment by ssiekmann** [comment]
Group discussion on Tuesday, 8/1 - decision is to adopt the [Geekfeminism CoC](https://geekfeminism.org/about/code-of-conduct/ )

Reports of harrassment can be made to any of the following individuals:

Than
Brennan
Sascha
