### ISSUE TITLE
Use a starter app package to scaffold the application architecture 

### ISSUE THREAD

**Issue by goldenapples** [PortlandAssembly/The-project#4]
I've been looking into a couple different starter app packages that are close to the architecture (a Flask app thats easily containerizable, ability to use an external database service like Firebase) that we've discussed. I'm opening this issue for discussion about the merits of each.

**Comment by goldenapples** [comment]
[**Flask User starter app**](https://github.com/lingthio/Flask-User-starter-app)

Looks like a nice enough setup. Uses Bootstrap for front-end framework. Flask-User requires a local database, so we'd have to run PostgreSQL as part of the application, so that's probably the tradeoff for this one. The [Heroku Postgres addon](https://devcenter.heroku.com/articles/heroku-postgresql) would work for that, and seems fairly reliable (99.5% uptime, with snapshots etc.). The cost for the addon is $9/mo, though, and since we're developing for organizations with minimal budgets, I'd like to avoid that.

**Comment by goldenapples** [comment]
[**Flask/React/Redux boilerplate**](https://github.com/dternyak/React-Redux-Flask)

Flask app framework using React front end. Comes with Material UI styles. This one also includes a local database - mysql in this case. Personally I like working in React, so the front end is nice for me. I know there's a bit of a learning curve to React (or any javascript app framework) over standard templating systems like jinja2 that is built into flask.

**Comment by blujan** [comment]
So seems the case that nothing supports external database services that you've found yet? So that leaves us the choice of stomaching a local database (and the management of it) or building/modifying the framework to allow for it.

**Comment by goldenapples** [comment]
Well, its not impossible at all to use an external database. [Python-firebase](https://github.com/ozgur/python-firebase) looks to be the tool to plug in to. There seems to be plenty of documentation out there for using Firebase with Google App Engine, which is similar enough architecture to a Flask app that I don't think it would be too difficult to find answers to any challenges we come across. I'm just not seeing a good starter pack that includes it off-the-shelf.

More significantly, I'm starting to question the complexity and cost that an external database adds, especially as we're looking to make this easily deployable by organizations. Every additional service we make someone sign up for in order to run this app adds a bit of technical challenge to getting it up and running.  And I'm not really sure how to estimate the requirements of the app yet. Firebase (or AWS Dynamo, or whatever) have a free plan that most networks I can picture running would probably fit - as long as we're very careful about limiting how much data we store and transfer. But when you get beyond that free plan, it can get expensive really quickly.
